export const metadata = {
    title: 'Next JS',
    decription: 'Generated by Next JS',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}